<?xml version="1.0" encoding="utf-8"?><Database Name="DB_HCS_HORE_KPT" Class="reRegistration2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.14.101.101\shpol;Initial Catalog=DB_HCS_HORE_KPT;User ID=sqlservices;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_HCS_HORE_KPTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_T_reREGISTRATION2" Member="TBL_T_reREGISTRATION2s">
    <Type Name="TBL_T_reREGISTRATION2">
      <Column Name="NRP" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAMA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TEMPAT_LAHIR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TEMPAT_LAHIR_OTHERS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TGL_LAHIR" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="JENIS_KELAMIN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_KTP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALAMAT_KTP_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALAMAT_KTP_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KOTA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROVINSI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KODE_POS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALAMAT_DOMISILI_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALAMAT_DOMISILI_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KOTA_DOMISILI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROVINSI_DOMISILI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KODE_POS_DOMISILI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_HP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AGAMA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GOL_DARAH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TGL_MASUK_KPP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TGL_MASUK_GROUP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PENDIDIKAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PENDIDIKAN_OTHERS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UNIVERSITAS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UNIVERSITAS_OTHERS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TGL_LULUS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UKURAN_BAJU" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UKURAN_SEPATU" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAMA_PASANGAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JENIS_KELAMIN_PASANGAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HUBUNGAN_PASANGAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_PASANGAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TGL_LAHIR_PASANGAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TGL_MENIKAH_PASANGAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TGL_MENINGGAL_PASANGAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ALAMAT_PASANGAN_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALAMAT_PASANGAN_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KOTA_PASANGAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROVINSI_PASANGAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NEGARA_PASANGAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KODE_POS_PASANGAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_PASANGAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_KANTOR_PASANGAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_HP_PASANGAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAMA_ANAK_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JENIS_KELAMIN_ANAK_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HUBUNGAN_ANAK_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_ANAK_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TGL_LAHIR_ANAK_1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TGL_MENINGGAL_ANAK_1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ALAMAT_ANAK_1_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALAMAT_ANAK_1_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KOTA_ANAK_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROVINSI_ANAK_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NEGARA_ANAK_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KODE_POS_ANAK_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_ANAK_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_KANTOR_ANAK_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_HP_ANAK_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAMA_ANAK_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JENIS_KELAMIN_ANAK_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HUBUNGAN_ANAK_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_ANAK_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TGL_LAHIR_ANAK_2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TGL_MENINGGAL_ANAK_2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ALAMAT_ANAK_2_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALAMAT_ANAK_2_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KOTA_ANAK_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROVINSI_ANAK_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NEGARA_ANAK_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KODE_POS_ANAK_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_ANAK_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_KANTOR_ANAK_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_HP_ANAK_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAMA_ANAK_3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JENIS_KELAMIN_ANAK_3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HUBUNGAN_ANAK_3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_ANAK_3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TGL_LAHIR_ANAK_3" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TGL_MENINGGAL_ANAK_3" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ALAMAT_ANAK_3_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALAMAT_ANAK_3_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KOTA_ANAK_3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROVINSI_ANAK_3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NEGARA_ANAK_3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KODE_POS_ANAK_3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_ANAK_3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_KANTOR_ANAK_3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_HP_ANAK_3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAMA_ANAK_4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JENIS_KELAMIN_ANAK_4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HUBUNGAN_ANAK_4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_ANAK_4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TGL_LAHIR_ANAK_4" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TGL_MENINGGAL_ANAK_4" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ALAMAT_ANAK_4_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALAMAT_ANAK_4_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KOTA_ANAK_4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROVINSI_ANAK_4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NEGARA_ANAK_4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KODE_POS_ANAK_4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_ANAK_4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_KANTOR_ANAK_4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_HP_ANAK_4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAMA_AYAH_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JENIS_KELAMIN_AYAH_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HUBUNGAN_AYAH_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_AYAH_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TGL_LAHIR_AYAH_KANDUNG" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IS_MENINGGAL_AYAH_KANDUNG" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TGL_MENINGGAL_AYAH_KANDUNG" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ALAMAT_AYAH_KANDUNG_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALAMAT_AYAH_KANDUNG_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KOTA_AYAH_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROVINSI_AYAH_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NEGARA_AYAH_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KODE_POS_AYAH_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_AYAH_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_KANTOR_AYAH_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_HP_AYAH_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAMA_IBU_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JENIS_KELAMIN_IBU_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HUBUNGAN_IBU_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_IBU_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TGL_LAHIR_IBU_KANDUNG" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IS_MENINGGAL_IBU_KANDUNG" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TGL_MENINGGAL_IBU_KANDUNG" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ALAMAT_IBU_KANDUNG_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALAMAT_IBU_KANDUNG_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KOTA_IBU_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROVINSI_IBU_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NEGARA_IBU_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KODE_POS_IBU_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_IBU_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_KANTOR_IBU_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_HP_IBU_KANDUNG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAMA_AYAH_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JENIS_KELAMIN_AYAH_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HUBUNGAN_AYAH_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_AYAH_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TGL_LAHIR_AYAH_MERTUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IS_MENINGGAL_AYAH_MERTUA" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TGL_MENINGGAL_AYAH_MERTUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ALAMAT_AYAH_MERTUA_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALAMAT_AYAH_MERTUA_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KOTA_AYAH_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROVINSI_AYAH_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NEGARA_AYAH_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KODE_POS_AYAH_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_AYAH_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_KANTOR_AYAH_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_HP_AYAH_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAMA_IBU_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JENIS_KELAMIN_IBU_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HUBUNGAN_IBU_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_IBU_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TGL_LAHIR_IBU_MERTUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IS_MENINGGAL_IBU_MERTUA" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TGL_MENINGGAL_IBU_MERTUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ALAMAT_IBU_MERTUA_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALAMAT_IBU_MERTUA_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KOTA_IBU_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROVINSI_IBU_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NEGARA_IBU_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KODE_POS_IBU_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_IBU_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_KANTOR_IBU_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_HP_IBU_MERTUA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DATE_MODIFIED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PATH_UPLOAD_DATA_KARYAWAN" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PATH_UPLOAD_DATA_PASANGAN" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PATH_UPLOAD_DATA_ANAK" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NAMA_SAUDARA_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JENIS_KELAMIN_SAUDARA_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HUBUNGAN_SAUDARA_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_SAUDARA_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TGL_LAHIR_SAUDARA_1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TGL_MENINGGAL_SAUDARA_1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ALAMAT_SAUDARA_1_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALAMAT_SAUDARA_1_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KOTA_SAUDARA_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROVINSI_SAUDARA_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NEGARA_SAUDARA_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KODE_POS_SAUDARA_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_SAUDARA_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_KANTOR_SAUDARA_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_HP_SAUDARA_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAMA_SAUDARA_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JENIS_KELAMIN_SAUDARA_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HUBUNGAN_SAUDARA_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_SAUDARA_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TGL_LAHIR_SAUDARA_2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TGL_MENINGGAL_SAUDARA_2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ALAMAT_SAUDARA_2_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALAMAT_SAUDARA_2_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KOTA_SAUDARA_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROVINSI_SAUDARA_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NEGARA_SAUDARA_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KODE_POS_SAUDARA_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_SAUDARA_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_TLP_KANTOR_SAUDARA_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NO_HP_SAUDARA_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FILE_KTP" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NO_NPWP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FILE_NPWP" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VAKSIN_1" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="VAKSIN_2" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="JENIS_VAKSIN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>